[build]
builder = "nixpacks"

[deploy]
startCommand = "uv run uvicorn backend.main:app --log-config=log_config.yaml --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
restartPolicyType = "on_failure"
