{
    "type": "combined",
    "vessels": [
        {
            "VesselID": 38,
            "VesselName": "Yakima",
            "Mmsi": 366772750,
            "DepartingTerminalID": 13,
            "DepartingTerminalName": "Lopez Island",
            "DepartingTerminalAbbrev": "LOP",
            "ArrivingTerminalID": 1,
            "ArrivingTerminalName": "Anacortes",
            "ArrivingTerminalAbbrev": "ANA",
            "Latitude": 48.57093,
            "Longitude": -122.882872,
            "Speed": 0,
            "Heading": 219,
            "InService": true,
            "AtDock": true,
            "LeftDock": null,
            "Eta": null,
            "EtaBasis": null,
            "ScheduledDeparture": "/Date(1753465500000-0700)/",
            "OpRouteAbbrev": [
                "ana-sj"
            ],
            "VesselPositionNum": 1,
            "SortSeq": 20,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467842000-0700)/",
            "VesselWatchShutID": 3,
            "VesselWatchShutMsg": "Vessel to return to service for 445p Anacortes to FH.\n",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. "
        },
        {
            "VesselID": 69,
            "VesselName": "Samish",
            "Mmsi": 367649320,
            "DepartingTerminalID": 1,
            "DepartingTerminalName": "Anacortes",
            "DepartingTerminalAbbrev": "ANA",
            "ArrivingTerminalID": 15,
            "ArrivingTerminalName": "Orcas Island",
            "ArrivingTerminalAbbrev": "ORI",
            "Latitude": 48.522263,
            "Longitude": -122.733868,
            "Speed": 15.3,
            "Heading": 276,
            "InService": true,
            "AtDock": false,
            "LeftDock": "/Date(1753467155000-0700)/",
            "Eta": "/Date(1753470600000-0700)/",
            "EtaBasis": "Vessel Samish departed Anacortes going to Orcas and using vessel Samish closest location data from Jul 25 2025  7:52AM",
            "ScheduledDeparture": "/Date(1753466100000-0700)/",
            "OpRouteAbbrev": [
                "ana-sj"
            ],
            "VesselPositionNum": 2,
            "SortSeq": 20,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467848000-0700)/",
            "VesselWatchShutID": 18,
            "VesselWatchShutMsg": "Vessel not in service",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. ",
            "cachedDelay": "18 min late"
        },
        {
            "VesselID": 2,
            "VesselName": "Chelan",
            "Mmsi": 366709770,
            "DepartingTerminalID": 10,
            "DepartingTerminalName": "Friday Harbor",
            "DepartingTerminalAbbrev": "FRH",
            "ArrivingTerminalID": 1,
            "ArrivingTerminalName": "Anacortes",
            "ArrivingTerminalAbbrev": "ANA",
            "Latitude": 48.5389,
            "Longitude": -123.01223,
            "Speed": 8.6,
            "Heading": 14,
            "InService": true,
            "AtDock": false,
            "LeftDock": "/Date(1753467728000-0700)/",
            "Eta": "/Date(1753471800000-0700)/",
            "EtaBasis": "Vessel Chelan departed Friday Harbor going to Anacortes and using vessel Chelan closest location data from Jul 24 2025 11:13AM",
            "ScheduledDeparture": "/Date(1753466100000-0700)/",
            "OpRouteAbbrev": [
                "ana-sj"
            ],
            "VesselPositionNum": 3,
            "SortSeq": 20,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467838000-0700)/",
            "VesselWatchShutID": 2,
            "VesselWatchShutMsg": "VesselWatch data temporarily unavailable.\n",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. ",
            "cachedDelay": "27 min late"
        },
        {
            "VesselID": 33,
            "VesselName": "Tillikum",
            "Mmsi": 366773090,
            "DepartingTerminalID": 15,
            "DepartingTerminalName": "Orcas Island",
            "DepartingTerminalAbbrev": "ORI",
            "ArrivingTerminalID": 10,
            "ArrivingTerminalName": "Friday Harbor",
            "ArrivingTerminalAbbrev": "FRH",
            "Latitude": 48.58018,
            "Longitude": -122.899115,
            "Speed": 10.8,
            "Heading": 183,
            "InService": true,
            "AtDock": false,
            "LeftDock": "/Date(1753467030000-0700)/",
            "Eta": "/Date(1753470180000-0700)/",
            "EtaBasis": "Vessel Tillikum departed Orcas going to Friday Harbor and using vessel Tillikum closest location data from Jul 24 2025  6:09PM",
            "ScheduledDeparture": "/Date(1753463700000-0700)/",
            "OpRouteAbbrev": [
                "ana-sj"
            ],
            "VesselPositionNum": 4,
            "SortSeq": 20,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467830000-0700)/",
            "VesselWatchShutID": 5,
            "VesselWatchShutMsg": "Out  of service ",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. ",
            "cachedDelay": "56 min late"
        },
        {
            "VesselID": 66,
            "VesselName": "Salish",
            "Mmsi": 367480010,
            "DepartingTerminalID": 17,
            "DepartingTerminalName": "Port Townsend",
            "DepartingTerminalAbbrev": "POT",
            "ArrivingTerminalID": 11,
            "ArrivingTerminalName": "Coupeville ",
            "ArrivingTerminalAbbrev": "COU",
            "Latitude": 48.15309,
            "Longitude": -122.674327,
            "Speed": 10.8,
            "Heading": 40,
            "InService": true,
            "AtDock": false,
            "LeftDock": "/Date(1753466460000-0700)/",
            "Eta": "/Date(1753468080000-0700)/",
            "EtaBasis": "Vessel Salish departed Port Townsend going to Keystone and using vessel Salish closest location data from Jul 25 2025  6:55AM",
            "ScheduledDeparture": "/Date(1753466400000-0700)/",
            "OpRouteAbbrev": [
                "pt-cou"
            ],
            "VesselPositionNum": 1,
            "SortSeq": 30,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467848000-0700)/",
            "VesselWatchShutID": 17,
            "VesselWatchShutMsg": "Vessel out of service due to fog",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. ",
            "cachedDelay": "1 min late"
        },
        {
            "VesselID": 52,
            "VesselName": "Kennewick",
            "Mmsi": 367479990,
            "DepartingTerminalID": 11,
            "DepartingTerminalName": "Coupeville ",
            "DepartingTerminalAbbrev": "COU",
            "ArrivingTerminalID": 17,
            "ArrivingTerminalName": "Port Townsend",
            "ArrivingTerminalAbbrev": "POT",
            "Latitude": 48.119573,
            "Longitude": -122.735318,
            "Speed": 13.1,
            "Heading": 211,
            "InService": true,
            "AtDock": false,
            "LeftDock": "/Date(1753466707000-0700)/",
            "Eta": "/Date(1753468380000-0700)/",
            "EtaBasis": "Vessel Kennewick departed Keystone going to Port Townsend and using vessel Salish closest location data from Jul 25 2025  7:34AM",
            "ScheduledDeparture": "/Date(1753466400000-0700)/",
            "OpRouteAbbrev": [
                "pt-cou"
            ],
            "VesselPositionNum": 2,
            "SortSeq": 30,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467849000-0700)/",
            "VesselWatchShutID": 19,
            "VesselWatchShutMsg": "VesselWatch data temporarily unavailable.\n",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. ",
            "cachedDelay": "5 min late"
        },
        {
            "VesselID": 18,
            "VesselName": "Kitsap",
            "Mmsi": 366772980,
            "DepartingTerminalID": 5,
            "DepartingTerminalName": "Clinton",
            "DepartingTerminalAbbrev": "CLI",
            "ArrivingTerminalID": 14,
            "ArrivingTerminalName": "Mukilteo",
            "ArrivingTerminalAbbrev": "MUK",
            "Latitude": 47.97469,
            "Longitude": -122.349218,
            "Speed": 0,
            "Heading": 327,
            "InService": true,
            "AtDock": true,
            "LeftDock": null,
            "Eta": null,
            "EtaBasis": null,
            "ScheduledDeparture": "/Date(1753468200000-0700)/",
            "OpRouteAbbrev": [
                "muk-cl"
            ],
            "VesselPositionNum": 1,
            "SortSeq": 40,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467837000-0700)/",
            "VesselWatchShutID": 6,
            "VesselWatchShutMsg": "Vessel information unavailable",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. ",
            "cachedDelay": "4 min late"
        },
        {
            "VesselID": 68,
            "VesselName": "Tokitae",
            "Mmsi": 367608860,
            "DepartingTerminalID": 14,
            "DepartingTerminalName": "Mukilteo",
            "DepartingTerminalAbbrev": "MUK",
            "ArrivingTerminalID": 5,
            "ArrivingTerminalName": "Clinton",
            "ArrivingTerminalAbbrev": "CLI",
            "Latitude": 47.950875,
            "Longitude": -122.297173,
            "Speed": 0,
            "Heading": 160,
            "InService": true,
            "AtDock": true,
            "LeftDock": null,
            "Eta": null,
            "EtaBasis": null,
            "ScheduledDeparture": "/Date(1753468200000-0700)/",
            "OpRouteAbbrev": [
                "muk-cl"
            ],
            "VesselPositionNum": 2,
            "SortSeq": 40,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467849000-0700)/",
            "VesselWatchShutID": 7,
            "VesselWatchShutMsg": "Route in service.",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. ",
            "cachedDelay": "10 min late"
        },
        {
            "VesselID": 36,
            "VesselName": "Walla Walla",
            "Mmsi": 366772780,
            "DepartingTerminalID": 12,
            "DepartingTerminalName": "Kingston",
            "DepartingTerminalAbbrev": "KIN",
            "ArrivingTerminalID": 8,
            "ArrivingTerminalName": "Edmonds",
            "ArrivingTerminalAbbrev": "EDM",
            "Latitude": 47.811237,
            "Longitude": -122.427605,
            "Speed": 16.4,
            "Heading": 75,
            "InService": true,
            "AtDock": false,
            "LeftDock": "/Date(1753467081000-0700)/",
            "Eta": "/Date(1753468440000-0700)/",
            "EtaBasis": "Vessel WallaWalla departed Kingston going to Edmonds and using vessel Spokane closest location data from Jul 25 2025 10:37AM",
            "ScheduledDeparture": "/Date(1753466700000-0700)/",
            "OpRouteAbbrev": [
                "ed-king"
            ],
            "VesselPositionNum": 1,
            "SortSeq": 50,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467846000-0700)/",
            "VesselWatchShutID": 9,
            "VesselWatchShutMsg": "VesselWatch data temporarily unavailable.\n",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. ",
            "cachedDelay": "6 min late"
        },
        {
            "VesselID": 30,
            "VesselName": "Spokane",
            "Mmsi": 366709780,
            "DepartingTerminalID": 8,
            "DepartingTerminalName": "Edmonds",
            "DepartingTerminalAbbrev": "EDM",
            "ArrivingTerminalID": 12,
            "ArrivingTerminalName": "Kingston",
            "ArrivingTerminalAbbrev": "KIN",
            "Latitude": 47.804378,
            "Longitude": -122.42382,
            "Speed": 16,
            "Heading": 234,
            "InService": true,
            "AtDock": false,
            "LeftDock": "/Date(1753467394000-0700)/",
            "Eta": "/Date(1753468740000-0700)/",
            "EtaBasis": "Vessel Spokane departed Edmonds going to Kingston and using vessel WallaWalla closest location data from Jul 25 2025 10:33AM",
            "ScheduledDeparture": "/Date(1753466700000-0700)/",
            "OpRouteAbbrev": [
                "ed-king"
            ],
            "VesselPositionNum": 2,
            "SortSeq": 50,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467850000-0700)/",
            "VesselWatchShutID": 16,
            "VesselWatchShutMsg": "Vessel in service",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. ",
            "cachedDelay": "12 min late"
        },
        {
            "VesselID": 32,
            "VesselName": "Tacoma",
            "Mmsi": 366772760,
            "DepartingTerminalID": 3,
            "DepartingTerminalName": "Bainbridge Island",
            "DepartingTerminalAbbrev": "BBI",
            "ArrivingTerminalID": 7,
            "ArrivingTerminalName": "Seattle",
            "ArrivingTerminalAbbrev": "P52",
            "Latitude": 47.622437,
            "Longitude": -122.509102,
            "Speed": 0,
            "Heading": 281,
            "InService": true,
            "AtDock": true,
            "LeftDock": null,
            "Eta": null,
            "EtaBasis": null,
            "ScheduledDeparture": "/Date(1753468200000-0700)/",
            "OpRouteAbbrev": [
                "sea-bi"
            ],
            "VesselPositionNum": 1,
            "SortSeq": 60,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467845000-0700)/",
            "VesselWatchShutID": 20,
            "VesselWatchShutMsg": "Vessel in service",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. ",
            "cachedDelay": "4 min late"
        },
        {
            "VesselID": 37,
            "VesselName": "Wenatchee",
            "Mmsi": 366749710,
            "DepartingTerminalID": 7,
            "DepartingTerminalName": "Seattle",
            "DepartingTerminalAbbrev": "P52",
            "ArrivingTerminalID": 3,
            "ArrivingTerminalName": "Bainbridge Island",
            "ArrivingTerminalAbbrev": "BBI",
            "Latitude": 47.602463,
            "Longitude": -122.340155,
            "Speed": 0,
            "Heading": 86,
            "InService": true,
            "AtDock": true,
            "LeftDock": null,
            "Eta": null,
            "EtaBasis": null,
            "ScheduledDeparture": "/Date(1753467900000-0700)/",
            "OpRouteAbbrev": [
                "sea-bi"
            ],
            "VesselPositionNum": 2,
            "SortSeq": 60,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467844000-0700)/",
            "VesselWatchShutID": 10,
            "VesselWatchShutMsg": "VesselWatch data temporarily unavailable. ",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. "
        },
        {
            "VesselID": 15,
            "VesselName": "Issaquah",
            "Mmsi": 366773040,
            "DepartingTerminalID": 7,
            "DepartingTerminalName": "Seattle",
            "DepartingTerminalAbbrev": "P52",
            "ArrivingTerminalID": 4,
            "ArrivingTerminalName": "Bremerton",
            "ArrivingTerminalAbbrev": "BRE",
            "Latitude": 47.598803,
            "Longitude": -122.40168,
            "Speed": 15.4,
            "Heading": 258,
            "InService": true,
            "AtDock": false,
            "LeftDock": "/Date(1753467196000-0700)/",
            "Eta": "/Date(1753471020000-0700)/",
            "EtaBasis": "Vessel Issaquah departed Colman going to Bremerton and using vessel Issaquah closest location data from Jul 25 2025  8:48AM",
            "ScheduledDeparture": "/Date(1753467000000-0700)/",
            "OpRouteAbbrev": [
                "sea-br"
            ],
            "VesselPositionNum": 1,
            "SortSeq": 70,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467849000-0700)/",
            "VesselWatchShutID": 12,
            "VesselWatchShutMsg": "Bremerton 12:20 pm / Seattle 1:30 pm CANCELLED",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. ",
            "cachedDelay": "3 min late"
        },
        {
            "VesselID": 17,
            "VesselName": "Kaleetan",
            "Mmsi": 366772990,
            "DepartingTerminalID": 4,
            "DepartingTerminalName": "Bremerton",
            "DepartingTerminalAbbrev": "BRE",
            "ArrivingTerminalID": 7,
            "ArrivingTerminalName": "Seattle",
            "ArrivingTerminalAbbrev": "P52",
            "Latitude": 47.571248,
            "Longitude": -122.592392,
            "Speed": 17.2,
            "Heading": 38,
            "InService": true,
            "AtDock": false,
            "LeftDock": "/Date(1753467409000-0700)/",
            "Eta": "/Date(1753470600000-0700)/",
            "EtaBasis": "Vessel Kaleetan departed Bremerton going to Colman and using vessel Kaleetan closest location data from Jul 25 2025  8:55AM",
            "ScheduledDeparture": "/Date(1753467000000-0700)/",
            "OpRouteAbbrev": [
                "sea-br"
            ],
            "VesselPositionNum": 2,
            "SortSeq": 70,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467848000-0700)/",
            "VesselWatchShutID": 21,
            "VesselWatchShutMsg": "Vessel Out of Service Due to Shortage of Crew",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. ",
            "cachedDelay": "7 min late"
        },
        {
            "VesselID": 19,
            "VesselName": "Kittitas",
            "Mmsi": 366772960,
            "DepartingTerminalID": 22,
            "DepartingTerminalName": "Vashon Island",
            "DepartingTerminalAbbrev": "VAI",
            "ArrivingTerminalID": 20,
            "ArrivingTerminalName": "Southworth",
            "ArrivingTerminalAbbrev": "SOU",
            "Latitude": 47.520163,
            "Longitude": -122.406173,
            "Speed": 5.4,
            "Heading": 23,
            "InService": true,
            "AtDock": false,
            "LeftDock": null,
            "Eta": null,
            "EtaBasis": "Vessel Kittitas departed Vashon going to Southworth and using vessel Cathlamet closest location data from Jul 25 2025 10:05AM",
            "ScheduledDeparture": null,
            "OpRouteAbbrev": [
                "f-v-s"
            ],
            "VesselPositionNum": 1,
            "SortSeq": 90,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467850000-0700)/",
            "VesselWatchShutID": 15,
            "VesselWatchShutMsg": "VesselWatch data temporarily unavailable. ",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. "
        },
        {
            "VesselID": 1,
            "VesselName": "Cathlamet",
            "Mmsi": 366773070,
            "DepartingTerminalID": 9,
            "DepartingTerminalName": "Fauntleroy",
            "DepartingTerminalAbbrev": "FAU",
            "ArrivingTerminalID": 22,
            "ArrivingTerminalName": "Vashon Island",
            "ArrivingTerminalAbbrev": "VAI",
            "Latitude": 47.5232,
            "Longitude": -122.396892,
            "Speed": 0,
            "Heading": 93,
            "InService": true,
            "AtDock": true,
            "LeftDock": null,
            "Eta": null,
            "EtaBasis": null,
            "ScheduledDeparture": "/Date(1753467000000-0700)/",
            "OpRouteAbbrev": [
                "f-v-s"
            ],
            "VesselPositionNum": 2,
            "SortSeq": 90,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467844000-0700)/",
            "VesselWatchShutID": 22,
            "VesselWatchShutMsg": "",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. "
        },
        {
            "VesselID": 28,
            "VesselName": "Sealth",
            "Mmsi": 366710820,
            "DepartingTerminalID": 22,
            "DepartingTerminalName": "Vashon Island",
            "DepartingTerminalAbbrev": "VAI",
            "ArrivingTerminalID": 9,
            "ArrivingTerminalName": "Fauntleroy",
            "ArrivingTerminalAbbrev": "FAU",
            "Latitude": 47.511047,
            "Longitude": -122.463318,
            "Speed": 0,
            "Heading": 214,
            "InService": true,
            "AtDock": true,
            "LeftDock": null,
            "Eta": null,
            "EtaBasis": null,
            "ScheduledDeparture": "/Date(1753467600000-0700)/",
            "OpRouteAbbrev": [
                "f-v-s"
            ],
            "VesselPositionNum": 3,
            "SortSeq": 90,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467849000-0700)/",
            "VesselWatchShutID": 23,
            "VesselWatchShutMsg": "Vessel Out of Service Due to Crewing",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. ",
            "cachedDelay": "7 min late"
        },
        {
            "VesselID": 65,
            "VesselName": "Chetzemoka",
            "Mmsi": 367463060,
            "DepartingTerminalID": 16,
            "DepartingTerminalName": "Point Defiance",
            "DepartingTerminalAbbrev": "PTD",
            "ArrivingTerminalID": 21,
            "ArrivingTerminalName": "Tahlequah",
            "ArrivingTerminalAbbrev": "TAH",
            "Latitude": 47.309512,
            "Longitude": -122.514077,
            "Speed": 7.9,
            "Heading": 13,
            "InService": true,
            "AtDock": false,
            "LeftDock": "/Date(1753467746000-0700)/",
            "Eta": "/Date(1753468500000-0700)/",
            "EtaBasis": "Vessel Chetzemoka departed Pt. Defiance going to Tahlequah and using vessel Chetzemoka closest location data from Jul 25 2025 10:25AM",
            "ScheduledDeparture": "/Date(1753466100000-0700)/",
            "OpRouteAbbrev": [
                "pd-tal"
            ],
            "VesselPositionNum": 1,
            "SortSeq": 110,
            "ManagedBy": 1,
            "TimeStamp": "/Date(1753467848000-0700)/",
            "VesselWatchShutID": 13,
            "VesselWatchShutMsg": "VesselWatch data temporarily unavailable.\n",
            "VesselWatchShutFlag": "0",
            "VesselWatchStatus": "0",
            "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. ",
            "cachedDelay": "27 min late"
        }
    ],
    "nextSailings": {
        "sea-bi": {
            "name": "Seattle / Bainbridge Island",
            "terminals": {
                "3": {
                    "terminal_name": "Bainbridge Island",
                    "sailings": [
                        {
                            "scheduled_departure": "11:30 AM",
                            "estimated_departure": "11:24 AM",
                            "estimated_delay": 4,
                            "vessel_position": 1,
                            "vessel_name": "Tacoma"
                        },
                        {
                            "scheduled_departure": "11:30 AM",
                            "estimated_departure": "11:34 AM",
                            "estimated_delay": 4,
                            "vessel_position": 1,
                            "vessel_name": "Tacoma"
                        },
                        {
                            "scheduled_departure": "12:20 PM",
                            "estimated_departure": "12:20 PM",
                            "estimated_delay": 0,
                            "vessel_position": 2,
                            "vessel_name": "Wenatchee"
                        },
                        {
                            "scheduled_departure": "1:15 PM",
                            "estimated_departure": "1:19 PM",
                            "estimated_delay": 4,
                            "vessel_position": 1,
                            "vessel_name": "Tacoma"
                        }
                    ]
                },
                "7": {
                    "terminal_name": "Seattle",
                    "sailings": [
                        {
                            "scheduled_departure": "11:25 AM",
                            "estimated_departure": "11:24 AM",
                            "estimated_delay": 0,
                            "vessel_position": 2,
                            "vessel_name": "Wenatchee"
                        },
                        {
                            "scheduled_departure": "11:25 AM",
                            "estimated_departure": "11:25 AM",
                            "estimated_delay": 0,
                            "vessel_position": 2,
                            "vessel_name": "Wenatchee"
                        },
                        {
                            "scheduled_departure": "12:25 PM",
                            "estimated_departure": "12:29 PM",
                            "estimated_delay": 4,
                            "vessel_position": 1,
                            "vessel_name": "Tacoma"
                        },
                        {
                            "scheduled_departure": "1:10 PM",
                            "estimated_departure": "1:10 PM",
                            "estimated_delay": 0,
                            "vessel_position": 2,
                            "vessel_name": "Wenatchee"
                        }
                    ]
                }
            }
        },
        "ed-king": {
            "name": "Edmonds / Kingston",
            "terminals": {
                "8": {
                    "terminal_name": "Edmonds",
                    "sailings": [
                        {
                            "scheduled_departure": "5:35 AM",
                            "estimated_departure": "5:41 AM",
                            "estimated_delay": 6,
                            "vessel_position": 1,
                            "vessel_name": "Walla Walla"
                        },
                        {
                            "scheduled_departure": "6:15 AM",
                            "estimated_departure": "6:29 AM",
                            "estimated_delay": 14,
                            "vessel_position": 2,
                            "vessel_name": "Spokane"
                        },
                        {
                            "scheduled_departure": "7:10 AM",
                            "estimated_departure": "7:16 AM",
                            "estimated_delay": 6,
                            "vessel_position": 1,
                            "vessel_name": "Walla Walla"
                        }
                    ]
                },
                "12": {
                    "terminal_name": "Kingston",
                    "sailings": [
                        {
                            "scheduled_departure": "4:45 AM",
                            "estimated_departure": "4:51 AM",
                            "estimated_delay": 6,
                            "vessel_position": 1,
                            "vessel_name": "Walla Walla"
                        },
                        {
                            "scheduled_departure": "5:30 AM",
                            "estimated_departure": "5:44 AM",
                            "estimated_delay": 14,
                            "vessel_position": 2,
                            "vessel_name": "Spokane"
                        },
                        {
                            "scheduled_departure": "6:25 AM",
                            "estimated_departure": "6:31 AM",
                            "estimated_delay": 6,
                            "vessel_position": 1,
                            "vessel_name": "Walla Walla"
                        }
                    ]
                }
            }
        }
    },
    "routesProcessed": [
        "sea-bi",
        "ed-king"
    ],
    "timestamp": "2025-07-25T18:24:21.193Z"
}
